### ISSUE TITLE
[CT-339] Persist dbt tags to Snowflake using object tagging feature

### ISSUE THREAD

**Issue by dweaver33** [dbt-labs/dbt-snowflake#104]
### Describe the feature
When tags are defined for various objects (tables, columns, etc), allow the option to persist these tags down to Snowflake using Snowflake's [object tagging](https://docs.snowflake.com/en/user-guide/object-tagging.html) feature.

### Describe alternatives you've considered
I've considered writing a macro to do this, but development time would prefer something more built-in. 

### Additional context
Tags are used in Snowflake to apply security and masking.  Having to maintain tags in two different areas is cumbersome and prone to error. 

### Who will this benefit?
Tags are useful in dbt for a number of reasons already known.  Persisting them into Snowflake would allow users to utilize Snowflake's security methods and prevent having to define tags in two different areas. 

### Are you interested in contributing this feature?
I can certainly contribute expertise and technical assistance.

**Comment by VersusFacit** [comment]
Hiya 👋 @dweaver33 

Thanks for submitting an issue, especially with a link to the docs -- helps by making sure we're both talking about the same thing 👍 

I totally appreciate the want to minimize the surface area where errors may be introduced. DRY code principles are espoused so often for a reason--a darn good reason. 

However, my major concern with this feature isn't a demonstrated use case or lack of principle but rather that tags in dbt seem to be semantically different from tags in Snowflake.

As you can see in [our docs](https://docs.getdbt.com/reference/resource-configs/tags), dbt tags are string values that can be assigned to objects in lists.

But, as seen in those docs you linked, Snowflake tags 
> can be assigned an arbitrary string value upon assigning the tag to a Snowflake object. Snowflake stores the tag and its string value as a key-value pair.

dbt tags do not support that key-value pair functionality. They are a different kind of metadata mechanism (one can argue if it's more or less useful). Therefore, to tie your dbt tags to your Snowflake tags is to make a deliberate design choice, namely to restrict your own ability to take advantage of Snowflake's featureset. That's a perfectly reasonable thing to do if your team decides that's in its best interest. That said, having that built-in to dbt-snowflake would be to force/encourage other users into this paradigm (i.e. where they may use `key-null` tags in their Snowflake database only). 

Seeing as we don't have evidence is a widespread requested feature, and it doesn't seem to support different database management approaches other enterprise users may have, I think the best solution would be a macro as opposed to a built-in feature, as you said!

**Comment by stkbailey** [comment]
@dweaver33 did you end up building a macro for this? Combined with tag-based masking policies, this would be a really great workflow

**Comment by dweaver33** [comment]
@stkbailey , unfortunately I did not.

**Comment by jamesweakley** [comment]
I realise this is a closed issue, but I'm looking at this same thing and wanted to propose an alternative.

Firstly to broaden this a little, BigQuery has an equivalent key-value pair concept called "[labels](https://cloud.google.com/bigquery/docs/labels-intro)". I also wouldn't be surprised to see something like this appear in Databrick's upcoming Unity Catalog.

Redshift and Azure both have resource tagging, but they appear to relate to surrounding infrastructure rather than database object so we can leave them out for now.

The subtle differences between BigQuery and Snowflake are:
- BigQuery labels apply only at the table/view level only, not column
- BigQuery labels are applied in isolation to each table, but Snowflake's tags are first-class, reusable objects that may reside in some other schema ([example](https://docs.snowflake.com/en/user-guide/tag-based-masking-policies.html#example-1-protect-column-data-based-on-the-masking-policy-directly-assigned-to-the-tag))
- To add to the confusion, an empty-string label in BigQuery is called a tag

I want to propose that instead of leveraging dbt tags, we use a convention within the "meta" config element named "database_tags". Within that, you can define name-value tags at the table/view level and at the individual column level (Snowflake only).

```

{{ 
    config(
        materialized='view',
        meta={
            'database_tags':{
                'table': {
                    'accounting_row_string': 'visible'
                },
                'column':{
                    'ACCOUNT_NAME':{
                        'accounting_col_string': 'visible'
                    },
                    'ACCOUNT_NUMBER':{
                        'accounting_col_string': 'visible'
                    }
                }
            }
        }
    ) 
}}
select ACCOUNT_NAME, ACCOUNT_NUMBER from {{ref('accounts_raw')}}
```

I have a prototype of a macro which applies these tags during on-run-end, currently it's Snowflake-only but could be extended to BigQuery.

Planning to publish it within a new package, unless anyone can think of a better place (dbt-utils?). I don't think it belongs in core, given it's a convention that not everyone will agree with.

**Comment by jamesweakley** [comment]
The other option is to use delimiters to shoehorn the key-value pairs into the tags, plus some indicator that it's a tag intended for the database.
e.g. "database:my_tag:my_value"

**Comment by dweaver33** [comment]
@jamesweakley, I would be very interested in seeing this macro. We are a snowflake shop.

**Comment by jamesweakley** [comment]
This is an incredibly rough draft, still some bugs but it should work as a POC.
https://gist.github.com/jamesweakley/dff5df8fb6565e07d707d34eaaf63da7
save into the macros folder, then add this to dbt_project.yml:
```
on-run-end: "{{ apply_tags_to_snowflake(results) }}"
```

**Comment by Andylaugen3** [comment]
Another snowflake shop here, and was looking for a way to make tag-based masking policies applied at dbt-runtime. 
Thank you for sharing @jamesweakley!

**Comment by mahsa-elemy** [comment]
@jamesweakley Thank you for sharing! I was wondering if this macro has published as a Package? The macro that you shared is it the final version? or since August there have been modifications to this?
We also use Snowflake and dbt in our company and would want to highly utilize what dbt offers to create tags for tables/columns in Snowflake for masking purposes.

**Comment by jamesweakley** [comment]
@mahsa-elemy what I linked is the extent of it at the moment, and I didn't end up putting it in a package yet.

@martinguindon, would you be happy to have this macro in dbt-snowflake-utils? I'm happy to open a PR if you agree

**Comment by MartinGuindon** [comment]
> @MartinGuindon, would you be happy to have this macro in dbt-snowflake-utils? I'm happy to open a PR if you agree

Sure. That package is in dire need of love, this would be the opportunity for us to spend some time on it! :)

**Comment by jamesweakley** [comment]
@gmatsonANSYS 

> From a use case - I have tested the tagging through model configs, but would love to see the column based meta tags happen on .yml files next to the documentation and testing lines. 

In the PR above, I switched it to use yml, check out the readme. I agree it looks nicer and better to manage, and allowed me to get rid of a level of nesting.

**Comment by DavidfNZ** [comment]
We are working on getting tag-based masking in Snowflake using dbt, so also very keen on hearing from anyone trying this out.

**Comment by jamesweakley** [comment]
For those looking for a quick summary:
- dbt Labs are not planning to bridge dbt tags with Snowflake tags as they are fundamentally different
- The dbt-snowflake-utils package by Montreal Analytics now has a macro that creates Snowflake tags from model/column meta: https://github.com/Montreal-Analytics/dbt-snowflake-utils#snowflake_utilsapply_meta_as_tags-source

**Comment by kamilamarcinekpgs** [comment]
I don't think that this macro is a sufficient solution. It applies all tags in the on-run-end hook, which might cause 2-10 mins gaps (in some of our cases) between creating a populated table, and creating a tag. This is true for non-incremental only, but still is a deal-breaker for using the tag-based masking policies. We cannot have our data masked "some time" after inserting, it should be transactional.
