### ISSUE TITLE
Update `dbt debug` to also check that the database and warehouse fields are correct

### ISSUE THREAD

**Issue by sidpatel13** [dbt-labs/dbt-snowflake#1118]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently dbt debug runs `select 1 as id`  ([link](https://github.com/dbt-labs/dbt-snowflake/blob/5da6fdbfd0895cf86c49dd2b95d89d3d2a57aa70/dbt/adapters/snowflake/impl.py#L302)). And seems like snowflake will allow you to do that without correct database/warehouse. This means that this command will pass regardless of whether the warehouse, database info provided is correct. 

### Expected Behavior

`dbt debug` should fail if the warehouse or database info is incorrect.

### Steps To Reproduce

Run dbt debug with wrong config values for database and warehouse. It will still pass.

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-snowflake:
```

**Comment by amychen1776** [comment]
Taking a look at this - this is expected behavior even in Snowflake 
![image](https://github.com/user-attachments/assets/e0ebc856-3cb6-4ca1-a5a1-01982003ff4c)

For the debug command that we are running (`select 1 as id`) - it makes sense that it wouldn't check the database. We aren't selecting an object in the database. For that, I don't see us updating. For warehouse - this would be an enhancement, even on Snowflake's capabilities with that query.

**Comment by amychen1776** [comment]
At this time, this is not something we intend to change because the behavior is expected on Snowflake.
