### ISSUE TITLE
[CT-453] Add support for WHEN NOT MATCHED, INSERT incremental update option for Snowflake

### ISSUE THREAD

**Issue by joshuataylor** [dbt-labs/dbt-snowflake#129]
### Describe the feature
With Snowflake, we have a table that should be append only, so we don't need to merge old results, only do this:

https://docs.snowflake.com/en/sql-reference/sql/merge.html#deterministic-results-for-insert

```
WHEN NOT MATCHED ... THEN INSERT
```

This means we won't get duplicates for the `unique_key` set in dbt.

### Describe alternatives you've considered
Just using the merge, but this can take a while.

### Additional context
This is great for event tables where it's a table with extra processing done to it. Kind of like a materialized view.

### Who will this benefit?
Users who have event tables that don't change, or have metadata tables that don't change.

### Are you interested in contributing this feature?
Yes, and happy to champion this feature and document it.

**Comment by jtcohen6** [comment]
Hey @joshuataylor, thanks for opening! Have you tried defining an incremental model _without_ a `unique_key`? That has the effect of running `insert into`, i.e. "append-only":

https://github.com/dbt-labs/dbt-snowflake/blob/184eaeb3fa65fb4090d811ea0fa6b7da3ea94574/dbt/include/snowflake/macros/materializations/merge.sql#L1-L23

On `dbt-spark`, we have an explicit incremental strategy named `append` for this behavior. On most other adapters, this behavior is implicitly supported via one of the existing strategies when `unique_key` is not defined. Might make a lot of sense to rationalize this behavior across adapters! (cc @VersusFacit)

**Comment by joshuataylor** [comment]
Removing the unique_key sounds like a good quickfix, but the WHEN NOT MATCHED will then not insert if the record accidentally is in the resultset.

**Comment by jtcohen6** [comment]
_Ah!_ Sorry, I misunderstood the original issue — you're totally right.

> Just using the merge, but this can take a while.

It sounds like performance is your main motivation here. A couple options to try:
- You can try using the `delete+insert` strategy instead. Anecdotally, some users have found this to be faster
- There's an open PR that proposes to speed up the `merge` strategy by using a view instead of a temp table for the intermediate results: https://github.com/dbt-labs/dbt-snowflake/pull/93
- _Your proposal in this issue:_ We could add logic [here](https://github.com/dbt-labs/dbt-core/blob/204d53516a08a619ebea69b68aa8138dd1814f54/core/dbt/include/global_project/macros/materializations/models/incremental/merge.sql#L35-L41) saying that, if the user has configured `merge_update_columns = []` ([docs](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#strategy-specific-configs)), dbt should totally skip templating the `when matched then update set` statement. In the meantime, you could try this with just `merge_update_columns = ['id']` (or whatever your `unique_key` column is named), to see if that speeds things up. My hunch is that the row-by-row `unique_key` match is the more expensive part of the operation, relative to the column-by-column update — but I could be wrong, and even so, every little bit may help.

**Comment by joshuataylor** [comment]
Sounds great, will have a look at the delete+insert

With regards to last point, yes, when using the when matched part is very slow with Snowflake, and using insert only is MUCH faster - atleast from our testing on 50m rows/800m rows.

**Comment by stijn-meersman** [comment]
I have a similar requirement, I want to do a merge to insert records if they do not exist yet, without updating them.
The problem with adding the unique key to the merge_update_columns is that you are now needlessly updating records which is bad for performance.

I think that making sure that when `merge_update_columns = []`, then no `when matched then update set` statement is added is the best solution.
