### ISSUE TITLE
[CT-739] Reducing the row limit in Snowflake account breaks dbt run process

### ISSUE THREAD

**Issue by msardana94** [dbt-labs/dbt-snowflake#174]
### Describe the bug
I was working with Snowflake Support to reduce the row limit for the Snowsight UI for our account to improve user experience. A side effect of that is `show schema` command is also impacted. Currently the maximum limit for `show terse schemas in database` is hard coded to 10,000 [here](https://github.com/dbt-labs/dbt-snowflake/blob/0829bd362568cb4003c05f4cd9f6a7dfd90cc5a6/dbt/include/snowflake/macros/adapters.sql#L101)

### Steps To Reproduce
You can easily reproduce this error by running `show terse schemas in database analytics_prod limit 20000;` in snowflake. Default limit is 10000 and this will raise an error. Similarly reducing the default to 200 will cause the dbt sql `show terse schemas in database analytics_prod limit 10000` getting error out.

### Expected behavior
This should be a configurable option I feel. Not sure if we can use some other sql to list schemas (i.e. `information_schema`)

### Additional context
As a stop gap, I was able to workaround this by overriding the macro `snowflake__list_schemas` in our dbt project but definitely not an ideal solution.

**Comment by jtcohen6** [comment]
@msardana94 Sorry for the delay getting back to you here.

Based on a quick search of the Snowflake docs, I'm guessing that the parameter you're describing here is `ROWS_PER_RESULTSET` (https://docs.snowflake.com/en/sql-reference/parameters.html#rows-per-resultset).

Is your goal to reduce the row limit for _all_ queries in your Snowflake account? It's not unreasonable to want to limit BI-style queries (in Snowsight UI) to fewer than 10k rows, but dbt will need this metadata in order to populate its runtime cache, and in order to correctly generate documentation.

I'd recommend finding a way to set this limit for some users, but not for dbt. Otherwise, there is going to be a hard trade-off between:
- the number of rows users can return from Snowsight queries
- the number of sources/models/seeds/snapshots you can have in your dbt project

---

The reason to include the `limit` clause at all is:
> If LIMIT rows is omitted, the command results in an error if the result set is larger than 10K rows.

That may be preferable, honestly, compared to returning missing / incorrect results...

**Comment by msardana94** [comment]
@jtcohen6 sorry for delayed response. Your explanation makes sense to me. I didn't realise that not having limit will result in an error altogether.

I explored the user session parameters you mentioned and it temporarily solves our use case. We are good to close this for now.
