### ISSUE TITLE
[CT-853] Query tag should be set on the session level and not unset for global query tags

### ISSUE THREAD

**Issue by joshuataylor** [dbt-labs/dbt-snowflake#199]
### Describe the feature
When setting the `query_tag` this is constantly set/unset between queries, slowing down the time for runs on high latency.

This is the case when putting `+query_tag`, which is then set/unset. This is good, this is how it should be if connections aren't being remade (ie connection reuse).

However this should be set on the `session_parameters` level when it's passed in via a dbt `profiles.yml` level, where it has to execute another query. I'm 250ms-280ms away from us-east-1, so this has to do another connection per one of these, which drastically slows down the queries.
![image](https://user-images.githubusercontent.com/225131/179513465-a1bc1fd9-0dd0-40bd-a88e-b50b99c76c5c.png)

### Describe alternatives you've considered
Living with it. :(

### Additional context
This does a lot of queries, see:
![image](https://user-images.githubusercontent.com/225131/179513636-162a6d81-c71a-4ee3-952f-0aad411afd7c.png)

### Who will this benefit?
People with slow connections, or dbt with Snowflake just being faster in general.

### Are you interested in contributing this feature?
yes

**Comment by jtcohen6** [comment]
@joshuataylor Thanks for opening the issue, and the PR to fix it!

I follow what you mean. When `query_tag` is set in `profiles.yml`, it actually has the effect of running this query after each connection is opened:

https://github.com/dbt-labs/dbt-snowflake/blob/d1653859147263b52b96fe1bfecfee25b50522b9/dbt/adapters/snowflake/connections.py#L280-L283

Rather than passing it in as an argument when initializing the connection itself.
