### ISSUE TITLE
[CT-1031] Allow user to write arbitrary join condition for merge into in incremental model

### ISSUE THREAD

**Issue by NiallRees** [dbt-labs/dbt-snowflake#231]
### Describe the feature
It's now possible to provide a list of columns to join on in the merge statement, but this still doesn't give complete flexibility. For example, I have a model where I'd like to supplement a primary key equality condition with an [equal_null](https://docs.snowflake.com/en/sql-reference/functions/equal_null.html) on the clustered column, which can sometimes be null. That today isn't possible as dbt always puts an `=` operator on the unique_keys specified.

As an alternative to the existing `unique_key` config, it would be very helpful if I could write a complete join expression for more complex use cases.

### Additional context
Please include any other relevant context here.

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

### Are you interested in contributing this feature?
Let us know if you want to write some code, and how we can help.

**Comment by jtcohen6** [comment]
@NiallRees I hear you asking for the ability to define custom "predicates," additional criteria for the join logic in dbt-templated `MERGE` statements that go beyond just the `unique_key` match. The original issue for this (https://github.com/dbt-labs/dbt-core/issues/3293) is motivated by very much the same use case — filtering on cluster keys for better merge performance.

This is work that @dave-connors-3 picked up several months ago, out of the goodness of his heart, but we didn't manage to get over the finish line:
- https://github.com/dbt-labs/dbt-core/pull/4546
- https://github.com/dbt-labs/dbt-snowflake/pull/78

Since then, there's been a bit of shuffling around in the incremental materialization. Specifically, in `dbt-snowflake`, we now _do_ accept `predicates` as a configuration (#196):

https://github.com/dbt-labs/dbt-snowflake/blob/340c3faaa43cff425c92161e4918beb171f1196f/dbt/include/snowflake/macros/materializations/incremental.sql#L52-L58

That "strategy macro" has the effect of calling a macro named `get_incremental_X_sql`, where `X` is the `incremental_strategy` you've configured for this model. The default on Snowflake is `merge` &rarr; [`get_incremental_merge_sql()` (defined in `dbt-core`)](https://github.com/dbt-labs/dbt-core/blob/a3b018fd3b0c789c976e0e189788471edef8acb1/core/dbt/include/global_project/macros/materializations/models/incremental/strategies.sql#L29-L40), which passes the arguments into the old macro name, [`get_merge_sql()` (also defined in `dbt-core`)](https://github.com/dbt-labs/dbt-core/blob/a3b018fd3b0c789c976e0e189788471edef8acb1/core/dbt/include/global_project/macros/materializations/models/incremental/merge.sql#L5).

That `default__get_incremental_merge_sql` just doesn't pass the `predicates` arg through — though it totally could / should!

One question: How would you want to define these predicates? Dave's idea was to define them like:
```sql
        incremental_predicates = [{
            'source_col' : 'customerorderid',
            'expression' : '> 1'
        }]
```

But I could also see just passing a raw SQL expression through:
```sql
        incremental_predicates = [
            "customerorderid > 1"
        ]
```

This is a fairly advanced need, and I think dbt may just want to trust the user to format their SQL correctly.

**Comment by NiallRees** [comment]
I'd love a system like Jeremy describes where the user can be trusted to format their SQL correctly. That might mean the user has to incorporate `DBT_INTERNAL_DEST_` prefixes into that merge statement, but I think that's fine. I'm personally after maximum flexibility, and should also make this feature easier to add as it just assumes whatever the user has supplied is valid.

**Comment by NiallRees** [comment]
PRs ready for review

**Comment by jtcohen6** [comment]
Good questions, both!

> Since we would need a similar resolution step for user supplied predicates, should that be moved into its own macro, or just live within each strategy?

I think our move should be to simply pull the `predicates` into each strategy, exactly as written, and then template them out into the appropriate spot in each `merge` / `delete` statement.

> I'd love a system like Jeremy describes where the user can be trusted to format their SQL correctly. That would mean the user has to incorporate `DBT_INTERNAL_DEST_` prefixes into that merge statement, but I think that's fine. I'm personally after maximum flexibility, which should also make this feature easier to add as it just assumes whatever the user has supplied is valid.

Agreed!

> Are these predicates only relevant for `MERGE` operations? Would someone also want to limit the table scan for `DELETE` statements? Right now i have a prototype that works for both, but wondering how relevant that second case would be.

Yes, I think it should be relevant for all types of statements that require scanning/modifying the existing table!

I'm going to close this issue in favor of https://github.com/dbt-labs/dbt-core/issues/5680. There will still be follow-on work to make `incremental_predicates` available in all adapters + strategies.
