### ISSUE TITLE
[CT-1417] dbt tests 000606 (57P03): No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.[Bug] <title>

### ISSUE THREAD

**Issue by Cipahi** [dbt-labs/dbt-snowflake#300]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Could not write back to snowflake even granted role 

### Expected Behavior

just want to see dbt pass and write back to tables in snowflake

### Steps To Reproduce

dev environment connected to github repositories 

### Relevant log output

```shell
dbt-snowflake
```

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-snowflake:
```

### Additional Context

![image](https://user-images.githubusercontent.com/36131706/198168701-e40df0ba-f508-4c60-b6a1-a3950e915941.png)

**Comment by jtcohen6** [comment]
Hey @Cipahi, this error often crops up when your Snowflake `user` doesn't have the right role / permissions to use the `warehouse` that you've configured in your connection profile (or that warehouse doesn't exist).

Since you're using dbt Cloud, could I ask you to reach out to dbt Cloud support for help instead? They'll be able to help you debug more quickly than we can over GitHub back-and-forth.

I'm going to close this one in the meantime, since I don't think it's a bug with code in `dbt-snowflake`.
