### ISSUE TITLE
[CT-1587] [Feature]  Allow ephemeral models to be temporary tables

### ISSUE THREAD

**Issue by rloredo** [dbt-labs/dbt-snowflake#338]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Add support to materialize ephemerals as temporary tables instead of just inserting the code as a cte.
Cte are slow and a full materialized table is not always required.
This way we preserve the ephemeral purpose improving speed.

### Describe alternatives you've considered

Instead of using an ephemeral materialization use table in another schema and have a post-hook that deletes the table.

### Who will this benefit?

Everyone using ephemeral models to add modularity and that use intermediate-intermediate models as tables for performance when they're not actually needed.

### Are you interested in contributing this feature?

yes but will take time

**Comment by dbeatty10** [comment]
Thanks for suggesting this idea @rloredo!

Between this and [#6234](https://github.com/dbt-labs/dbt-core/issues/6234), it seems like temp tables are in the air ❄️

The general idea of your feature suggestion has these essential qualities:
- Provide a table-based alternative to ephemeral materializations
- Don’t persist such tables beyond the end of dbt execution

I think the alternative you suggested using an [on-run-end hook](https://docs.getdbt.com/reference/project-configs/on-run-start-on-run-end) is the way to go for achieving those goals! 💥 

### "Temp" tables within a dbt "session"

Here’s a concrete example of using on-run-end hooks to mimic the behavior of Snowflake temporary tables (taken from [here](https://github.com/dbt-labs/dbt-core/issues/6234#issuecomment-1320766483:~:text=%22Temp%22%20tables%20within%20a%20dbt%20%22session%22)):

`my_data.sql`
```sql
{{ config(materialized="table") }}

select ...
from {{ ref('my_other_dbt_model') }}
```

`dbt_project.yml`
```
on-run-end:
  - "drop table if exists {{ ref('my_data') }};"
```

### Rationale

Here are a few reasons for this approach (rather than an ephemeral materialization variant that uses [Snowflake’s temporary tables](https://docs.snowflake.com/en/user-guide/tables-temp-transient.html#temporary-tables)):
- This approach is already possible today
- It works across other dbt adapters beyond just Snowflake
- It avoids re-materializing the table each time it is referenced. If it is used 3 times, it is still only created 1 time and then dropped at the end of the dbt execution

A key drawback of an approach that uses the ephemeral approach with temp tables is that it would end up re-creating the table every time it is referenced. If it is used 3 times, then it would be re-created 3 times.

Are there any good reasons that I’m overlooking for using Snowflake-native temp tables instead?

**Comment by ecerulm** [comment]
> It avoids re-materializing the table each time it is referenced. If it is used 3 times, it is still only created 1 time and then dropped at the end of the dbt execution

I think the idea was not re-materialize the snowflake-native table each time is referenced. Right now a model marked as ephemeral is  implemented as a CTE  that is re-evaluated" for each other  model that reference it.

 My expectation (and I think  @rloredo is the same) would be that the ephemeral would be implemented as a snowflake-native temp table that is materialized **once** for the whole run and will be reused for all models that reference it , **the same way a "full materialized table" model (deleted at the `on-run-end`) would be.**

Maybe this changes the meaning of "ephemeral" on dbt as per [current documentation](https://docs.getdbt.com/docs/build/materializations#ephemeral) and that is what the confusion is.

I guess a new materialization called "temporary" would be maybe more correct in the sense that "temporary" is could would not have the same Pro/Cons as the current [ephemeral Cons and Pros ](https://docs.getdbt.com/docs/build/materializations#ephemeral). This new materialization could be implemented as snowflake-native temp table in snowflake or as a regular table materialization with random suffix in the table name and an  implicit drop at the end of the run on other databases.

> Are there any good reasons that I’m overlooking for using Snowflake-native temp tables instead?

- in projects with lots of these  temp tables you will get lots of DROP TABLE IF EXISTS at the end of the run
	- this will happen regardless if the dbt run actually created these tables or not. For example if I have 50 of this temporary tables, and I do dbt run --select "+the_model_im_working_on_that_uses_0_temp_tables"  I would see 50 DROP TABLE commands that are **superflous**, add some **delay to the operation**, and clutter the query log.  **If using snowflake-native temp tables this won't happen**, we won't see the explicit DROP TABLE commands, and no delay will happens waiting for the 50 drops to finish.
	- it temporarily clutters the schema with many temporary table that are visible to other users.  **Snowflake-native temp tables are only visible in the current session**, other users or even other sessions for the same user can't see those. 
- Snowflake-native temp tables like transient tables, are not part of the "Time Travel" so there are some savings on storage cost for that as well.

**Comment by EliasHvideberg** [comment]
I completely agree with @ecerulm [response](https://github.com/dbt-labs/dbt-snowflake/issues/338#issuecomment-1562801058) above. The "temporary"-feature would be really nice for BigQuery as well.

I don't know why "triage" was removed without any further comments? I'm sure this feature would be helpful to a lot of people.

**Comment by GKTheOne** [comment]
I've only used "desktop" databases (ie, postgresql, mysql) and Snowflake. I believed that temporary tables are ubiquitous, but I'm assuming from an above comment (the second rationale [here](https://github.com/dbt-labs/dbt-snowflake/issues/338#issuecomment-1345736470)) that they may not be?
In my case I am generating ID's in an intermediate model to be used in a couple of downstream models. For me the session-only visibility, no time travel, and throwaway nature of a temporary table would be helpful.
