### ISSUE TITLE
[CT-2061] [Bug] Query tags not unset for view materialization

### ISSUE THREAD

**Issue by NiallRees** [dbt-labs/dbt-snowflake#456]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Query tags not unset for view materialization

### Expected Behavior

Query tags are unset for view materialization

### Steps To Reproduce

Set a query tag for a view, watch it not be unset

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-snowflake:
```

**Comment by dbeatty10** [comment]
Thanks for submitting a PR for this @NiallRees !

Since it was clear from your PR why the query tag wasn't being unset, I didn't go through the extra effort of reproducing this. A member of our Adapters team will review your PR when they are able.

A left some small comments on the PR, one for you, and one for the PR reviewer.
