### ISSUE TITLE
[ADAP-604] [Bug] 1.3.2 is showing as the latest tagged release. 1.5.1 should be.

### ISSUE THREAD

**Issue by nevdelap** [dbt-labs/dbt-snowflake#651]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

![image](https://github.com/dbt-labs/dbt-snowflake/assets/583807/02a982aa-44c0-4c19-9c5d-792413bd0bbf)

### Expected Behavior

1.5.1 is tagged as latest.

### Steps To Reproduce

Look at https://github.com/dbt-labs/dbt-snowflake or https://github.com/dbt-labs/dbt-snowflake/releases.

### Relevant log output

```shell
NA
```

### Environment

```markdown
NA
```

**Comment by dataders** [comment]
@nevdelap thanks for reporting! we're also frustrated by this. we're tracking it here: https://github.com/dbt-labs/dbt-release/issues/73. the problem is that we're not exactly sure is what's happening which will make tackling this more challenging.

in the meantime I've manually updated the tag to reflect reality. cheers!

**Comment by nevdelap** [comment]
Cheers @dataders.

**Comment by philippeboyd** [comment]
@dataders 
it seems 1.3.0 is still tagged as latest
![image](https://github.com/dbt-labs/dbt-snowflake/assets/3239656/0ca0d01f-27f8-48bb-82c9-2f2b3b211c41)
