### ISSUE TITLE
[ADAP-620] [Bug] Incremental materialization with "append" strategy does not wrap dml with explicit transaction

### ISSUE THREAD

**Issue by danielefrigo** [dbt-labs/dbt-snowflake#656]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running an incremental model with "append" incremental strategy, the INSERT statement is not wrapped with an explicit transaction.

### Expected Behavior

The INSERT statement should be wrapped as all other DML statements, leveraging the `snowflake_dml_explicit_transaction` macro.

### Steps To Reproduce

1. create a model with incremental materialization and set incremental_strategy = "append"
2. check run sql under target folder: the statement is not wrapped with `begin; commit; end;`

### Environment

```markdown
- OS: Linux
- Python: 3.8
- dbt-core: 1.4.6
- dbt-snowflake: 1.4.3
```

### Additional Context

Should be easily fixed adding this [here](https://github.com/dbt-labs/dbt-snowflake/blob/ed6ed81ec2f8b409b29dafe11ed47a75b477ffec/dbt/include/snowflake/macros/materializations/merge.sql#L44):

`{% macro snowflake__get_incremental_append_sql(get_incremental_append_sql) %}
    {% set dml = default__get_incremental_append_sql(get_incremental_append_sql) %}
    {% do return(snowflake_dml_explicit_transaction(dml)) %}
{% endmacro %}`

**Comment by dataders** [comment]
@danielefrigo great catch! would you be interested in opening the corresponding pull request? I'd be glad to help you get it over the finish line.

**Comment by dataders** [comment]
hey @danielefrigo, just took the time to reproduce your result. Correct me if I'm wrong but the insert logic you hope to have wrapped in a transaction is [`get_insert_into_sql`](https://github.com/dbt-labs/dbt-core/blob/9bb1250869d6d004f2a81656986bd03c03cf12da/core/dbt/include/global_project/macros/materializations/models/incremental/strategies.sql)'s, right?

I agree that this macro could be executed as a transaction, but I'm not sure what it would accomplish, because it is just a single SQL statement. I may be missing something, but I thought that transactions are helpful when executing a series of a related SQL statements. Instead the update logic of an append is just the following. right?

```sql
insert into TEST_DB.dbt_ajs.daniele ("ID", "FIRST_NAME", "LAST_NAME")
    (
        select "ID", "FIRST_NAME", "LAST_NAME"
        from TEST_DB.dbt_ajs.daniele__dbt_tmp
    )
```

**Comment by danielefrigo** [comment]
Let's start saying that I was overriding the `snowflake_dml_explicit_transaction`, and then I noticed that the statements resulting from this kind of materialization were behaving differently from others.
I agree with your analysis, but the same applies to other statements that are currently wrapped (e.g. [default__get_merge_sql](https://github.com/dbt-labs/dbt-snowflake/blob/641745fce153a97c0453b5213e3ff85c8e958bee/dbt/include/snowflake/macros/materializations/merge.sql#L30)), so I guessed this was intentionally done for some other reason like performance.
And this connects to my second question about Snowflake transactions management and hooks (
https://github.com/dbt-labs/dbt-core/issues/3480)
