### ISSUE TITLE
[CT-45] [Feature] Expose Snowflake query id in case of dbt test failure

### ISSUE THREAD

**Issue by tommyh** [dbt-labs/dbt-snowflake#82]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

When we get a dbt test failure, I often look through the debug logs to find the exact query which was run.  Having the `dbt_internal_test` query with `failures`, `should_warn`, and `should_error` are an amazing first step, but the issue is that when I rerun the query, it often passes.  If the debug logs (or the friendly logs) contained the `sfqid`, then I could easily modify the query to use snowflake's timetravel feature, so I can recreate the failing test and debug it further.

Right now, I see the following info is logged:

```
022-01-14 00:14:37.419997 (Thread-39): 00:14:37  On test.[redacted].c630bf19e2: /* {"app": "dbt", "dbt_version": "1.0.1", "profile_name": "user", "target_name": "default", "node_id": "[redacted]"} */
```

Related issue: https://github.com/dbt-labs/dbt-core/pull/2358

### Describe alternatives you've considered

Right now, I look through the snowflake query history to find the sfqid, which works but is a bit tedious.

### Who will this benefit?

Analytics engineers running dbt tests being able to track down issues faster.  Speed is critical because the standard edition of snowflake only allows for 1 day of timetravel, so you need to debug it quickly.

The easier it is to track down intermittent test issues the better, so that people are encouraged to write more.

### Are you interested in contributing this feature?

Sure!  I have a bit of experience with python (mostly ruby/javascript), but could figure it out if I know:
* people think this is a good idea (so it's not a waste of everyone's time)
* a point in the right direction

### Anything else?

I'm loving dbt!  Thanks for all of the hard work.

**Comment by smitthakkar1** [comment]
@jtcohen6 thank you for your answer above. I upgraded to dbt-snowflake `1.2.0` (same as dbt) and have access to `query_id` under `adapter_response` of `result` object but I get `null` query id when a query fails and it shows query id only for successful model run. Is that expected ?

**Comment by jtcohen6** [comment]
@smitthakkar1 you're right! That's because `adapter_response` is actually _never_ populated for failing queries. We can take one of two approaches here:
- Do here as `dbt-bigquery` does, and wrap query submissions in a [custom exception handler](https://github.com/dbt-labs/dbt-bigquery/blob/4bb481d1f1f817e87e0fd951260eebd155c65e9f/dbt/adapters/bigquery/connections.py#L204-L215) that [logs out the `job_id` before raising the exception](https://github.com/dbt-labs/dbt-bigquery/blob/4bb481d1f1f817e87e0fd951260eebd155c65e9f/dbt/adapters/bigquery/connections.py#L190-L199)
- Make changes within `dbt-core` to enable this pattern. Either by logging like above, or change the way that we `try`/`except` the execution of model materializations.

I prefer the second approach if possible; I'll open a `dbt-core` issue about this.

**Comment by smitthakkar1** [comment]
@jtcohen6 Thanks for your reply.

>We already do this, in dbt-snowflake. Even though the query_id doesn't appear in run_results.json, it does still appear in the debug-level logs

Any idea on how to access those debug level logs via dbt template and print it ?

**Comment by jaypeedevlin** [comment]
Given this is already in the debug logs, would y'all be open to optionally appending the query ID to the error message based on some config or env var?
