### ISSUE TITLE
[ADAP-1006] [CT-3321] DBT Models are not using Snowflake Result Cache/Query Cache

### ISSUE THREAD

**Issue by ankitsr92** [dbt-labs/dbt-snowflake#825]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Snowflake Query Cache states that if the a query is run multiple time within 24 hrs window across any warehouse result would be produced through result cache. Given the source table data has not changed.

When it comes to DBT Models, I executed my models once. Upon executing the models again in next 5 min I still see model sql's being executed and taking the same amount of time as Run 1. The base tables again have not changed this time.

Is it not contrary to Snowflake behaviour? Is it something with DBT backend code which is restricting this?

### Expected Behavior

Upon re-run dbt models again within 24 hrs time and with unchanged base tables, Snowflake query cache should be used and it should take considerably less amount of time compared to first run.

### Steps To Reproduce

Run any DBT Model on Snowflake
Run the model again post Run 1 completion
* Make sure base tables are not changed

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.9.12
- dbt-core: 1.5
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment]
Thanks for reaching out about this @ankitsr92.

Based on your description, it sounds like you are doing the following?
1. Execute all the models (presumably each of the underlying queries is cached by Snowflake)
2. Execute all the models again
3. [Notice that](https://community.snowflake.com/s/article/Understanding-Result-Caching) none of queries resulted in a cache hit

If so, then what happens if you do the following instead?
1. Execute only a single model
    - i.e., `dbt run --select my_model`
1. Execute only that same model again
    - i.e., `dbt run --select my_model`
    
Does it result in a cache hit or a cache miss?

**Comment by Dikootje** [comment]
Adding a test scenario: 
```sql 
-- create some dummy data
create or replace table test as 
select dateadd(day, 
            row_number() 
                over (order by seq4()),
                '1899-12-31'::date) as d_date 
from table(generator(rowcount => 109573));

select * from test; -- uses warehouse to compute
select * from test; -- no warehouse because of result cache

create or replace table test2 as 
select * from test; -- uses warehouse

create or replace table test2 as 
select * from test; -- uses warehouse
```

Looking in the query history: 
![image](https://github.com/dbt-labs/dbt-snowflake/assets/5430309/fea32017-bcef-4d00-8452-12623574a2ec)

The first select query (second to last one in the screenshot) is using the warehouse to return data. The third to last one doesnt use a warehouse because the query is returned from the result cache. 

Adding a `create or replace` always triggers the usage of a warehouse. So I dont think this is a bug in dbt-snowflake

**Comment by dbeatty10** [comment]
Based on the insights and research by @b-per and @Dikootje, it doesn't look like this is a bug in dbt-snowflake but rather just how "create table as" (CTAS) statements interact with the Snowflake query cache.

So I'm going to close this as "not planned".
