### ISSUE TITLE
Snowflake Account URL

### ISSUE THREAD

**Issue by Jacob-Holland-CKO** [dbt-labs/dbt-snowflake#87]
### Describe the feature
Make the account value fully configurable to allow for URLs that do not necessarily conform to the `snowflakecomputing.com` convention.

https://github.com/dbt-labs/dbt-snowflake/blob/36c36d08ebf438225ce8069d37afa369ce4e67b8/dbt/adapters/snowflake/connections.py#L28

Could become something like:

` _TOKEN_REQUEST_URL = 'https://{}/oauth/token-request'`

### Describe alternatives you've considered
Rewriting DNS records, changing security configuration of network

### Additional context
If an organisation derives it's own account value that doesn't necessarily conform to the standard hard-coded in the library it makes it impossible to properly connect from local clients to the snowflake account using dbt.

### Who will this benefit?
Snowflake users, more mature organisations that are maintaining a high degree security posture.

### Are you interested in contributing this feature?
Yes

**Comment by VersusFacit** [comment]
Hey @Jacob-Holland-CKO (and hi to your friends from CKO that 👍 -ed the post) 😄 

Okay, so, not being able to use dbt at all seems a pretty serious stumbling block. 
> If an organisation derives it's own account value that doesn't necessarily conform to the standard hard-coded in the library it makes it impossible to properly connect from local clients to the snowflake account using dbt.

^ this is particularly salient

However, I am struggling to find an example of it in Snowflake's documentation :x I strolled around the Snowflake docs and everything I can find ([this](https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#option-1-account-name-in-your-organization) for example and [even this](https://community.snowflake.com/s/article/How-To-Setup-SSO-with-Auth0-and-Snowflake-New-URL-Format-or-Privatelink) newer post) implies that there are all sorts of ways to change `<account_identifier>` but not the underlying `snowflake_computing.com`. 

By all means, point me in the right direction! I feel like there's secret knowledge here I ought to know more about.

In any event, there's a couple of solutions that come to mind right off the bat:
- your team forks this repo and overrides the url as you have in your PR (assuming that works without other nuance) <-- hopefully more tenable than resorting to network layer work 
- this repo is changed:
  1. totally override the Snowflake hostname to an open field <-- your linked PR's solution
  2. create an optional field which overrides the URL if present <-- introduces unwanted complexity to the semantics of a Snowflake `~/.dbt/profiles.yml` profile
  3. add a new optional field which changes the domain name (`domain`?) of the cluster but we retain Snowflake account identifier semantics <-- this seems straightforward and 'clean' and a possible fix

I appreciate you getting that PR up, but in its present form, it won't be merged. Changing the underlying URL universally will brick several thousand existing projects that do in fact use the standard library method for authenticating against Snowflake.

And then, there's the problem of what exactly does your URL look like? If option 3 could work, I'd file this as a good first issue, but if option 2 is the only way forward, I don't think this is something we have the appetite for.

Would love to hear your thoughts on this!

**Comment by anthu** [comment]
I was about to write the same thing like that would break basically every single configuration right now (while by far not that detailed as you).

While I also haven't seen anybody using a complete custom hostname for Snowflake, yet I image there are companies around doing so in private networks.

What we could do is to construct the OAuth URL using the `host` parameter instead of the `account` - see https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/adapters/snowflake/connections.py#L46. 
As the snowflake-python-connector anyway doing so - generating the `host` from the `account` (see https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/connection.py#L819-L825).

**Comment by VersusFacit** [comment]
Thanks for jumping in. Your comment aroused a forgotten suspicion I've had in the past and took me on an adventure. 🏃‍♀️ 

> yet I image there are companies around doing so in private networks.

Same. I asked because the desired form of URIs would alter the YAML tag complexity needed (i.e. implementation of an optional `domain` field or needing to actually overwrite the whole thing which would be far worse). Buuuut....

Wouldn't you know it, we found ✨ undefined behavior ✨ :
- in a personal project, I tested this with various permutations of `host` and `account` in `profiles.yml`, and indeed, `host` is a valid field for our `profiles.yml`
- the snowflake-python-connector repo requires `account` no matter what but like you said, can build `account` if it needs

I'd suggest that's your way forward. In the meantime, we'll have to get a PR up for the dbt docs to say yes this in fact does exist as an option. 😄 

Thanks for the links. Sped up my research.

**Comment by anthu** [comment]
☝️ Anyway - the OAuth token retrieval flow is implemented in this adapter repo and doesn't take custom URLs into account.

I have the feeling, that this issue has a valid point and would suggest to actually use the `host` field **if provided** here:
https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/adapters/snowflake/connections.py#L137

Let me ask around whether there might be some edge-cases where the OAuth flow needs to be routed through the `snowflakecomputing.com` domain while the queries are sent to a custom domain (can't imagine that this would be the case).

**Comment by Jacob-Holland-CKO** [comment]
Thanks very much for the lively chatter on this! You're both much quicker but I'll try to fill in some gaps as we go.

> However, I am struggling to find an example of it in Snowflake's documentation :x I strolled around the Snowflake docs and everything I can find (this for example and even this newer post) implies that there are all sorts of ways to change <account_identifier> but not the underlying .snowflakecomputing.com.

We make use of a [zero-trust application](https://www.perimeter81.com/glossary/zero-trust) setup which means the initial URL to which we connect is a string which we can completely define without the `snowflakecomputing.com` bit. This is more in case other organisations come to use the same security setup, you can hopefully just refer them to this post without having to draft another thorough response. 

> I appreciate you getting that PR 88 up, but in its present form, it won't be merged. Changing the underlying URL universally will brick several thousand existing projects that do in fact use the standard library method for authenticating against Snowflake.

Makes complete sense, don't want to break all Snowflake clients using dbt; but something we can refer to whilst sorting this out. 

In terms of solutions: 
- Quick & dirty: make use of the forked code (fine for short-term)
- More investigation: make use of the `host` value to construct our own `account` value

**Comment by anthu** [comment]
Just to make sure regarding the very last point:
`account` seems to be required in Snowflake Python Connector but it's actually used to construct the `host` property in case `host` is not provided explicitly. see linked code snippet posted above https://github.com/snowflakedb/snowflake-connector-python/blob/master/src/snowflake/connector/connection.py#L819-L825

**Comment by VersusFacit** [comment]
That's my understanding, but also, it's required [here](https://github.com/snowflakedb/snowflake-connector-python/blob/6aed496578fdc4c4ab527eb1eadb81fa24f12712/src/snowflake/connector/connection.py#L867), a little further down.

As for the oauth URL question, I like the idea of altering the oauth flow to allow for a generic `host` field in general for that element, but I frankly don't know the subtleties (nor how to discover the subtitles) of the oauth api endpoint where that token_url field is used. So, there very well may be a great argument to do that. I just don't have the requisite knowledge to be confident one way or another on the wisdom of this. [Everywhere I looked](https://docs.snowflake.com/en/user-guide/oauth-custom.html#step-2-call-the-oauth-endpoints) is defined in terms of the snowflakecomputing.com domain.

**Comment by VersusFacit** [comment]
@anthu Just circling back since I already have an update. So, apparently wanting a custom URL specifically for oauth token retrieval is something we've been approached about once before (we dug up a Notion page from the archives heh).

If we can confirm that there aren't any crazy caveats to the behavior in using the host field (or maybe even some specially defined field like `oauth_host` for our internal use), let's get a new issue opened up in this repo that references this one and offers some pointers to the right solution (whatever it ends up being). 😄 We'll invite a community contribution for it!

This seems like a relatively recently added feature to Snowflake. So, we're sort of finding ourselves miners in the dark, unexplored parts of the cavern.
