### ISSUE TITLE
[Bug] `use_anonymous_sproc=False` Should not drop stored procedure

### ISSUE THREAD

**Issue by noah-voltops** [dbt-labs/dbt-snowflake#910]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When building a model with the parameter set to false (`use_anonymous_sproc=False`), dbt logs show the following:

1. The non-anonymous style procedure query running ie: `CREATE OR REPLACE PROCEDURE...`; followed by
2. `drop procedure if exists ...`

I am wondering if the conditional on [line 257](https://github.com/dbt-labs/dbt-snowflake/blob/2c0b16f73f5c56fbc5ec9c278f3716f09473c416/dbt/adapters/snowflake/impl.py#L257) can be changed to not delete the procedure.

The code as-is:
```
if not use_anonymous_sproc:
    self.execute(
        f"drop procedure if exists {proc_name}()",
        auto_begin=False,
        fetch=False,
    )
```

### Expected Behavior

If the model configuration opts to **not** use an anonymous procedure, is it possible to still allow the procedure to persist without dropping it?

Maybe by using a secondary conditional to preserve the existing logic flow, or remove the following to enforce use_anonymous_sproc=True for the only solution for non-persisting procedures?

Is this a logic bug? Is this an intentional design decision to delete both anonymous and non-anonymous sproc?

### Steps To Reproduce

Build a python model with `use_anonymous_sproc=False`, the procedure will not be stored in Snowflake.

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-snowflake:
```

**Comment by dbeatty10** [comment]
Similar to the reasoning within https://github.com/dbt-labs/dbt-core/issues/9658#issuecomment-1965153103, the stored procedure in [`submit_python_job`](https://github.com/dbt-labs/dbt-snowflake/blob/2c0b16f73f5c56fbc5ec9c278f3716f09473c416/dbt/adapters/snowflake/impl.py#L200) is an internal implementation detail for dbt-snowflake to enable dbt Python models rather than a persistent object that we'd want to support.

So I'm closing this as "not planned".
