### ISSUE TITLE
[Bug]: can only concatenate list (not 'Table') to list when creating model

### ISSUE THREAD

**Issue by vinod-tgm** [dbt-labs/dbt-snowflake#962]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm encountering a limitation with this table, as I can only read 1k entries at a time. I attempted to create a model using a specific approach, but unfortunately, it's not functioning as expected. Instead, I'm encountering the following error message: `can only concatenate list (not 'Table') to list`.

Please recommend any other approach for this

```
{%- set chunk_size = 1000 -%}
{%- set offset_value = 0 -%}

{%- set query_template -%}
    select * from {{ source('schema', 'table') }}
    limit {{ chunk_size }} offset {{ offset_value }}
{%- endset -%}

{%- set results_list = [] -%}

{% for offset in range(0, 1000, chunk_size) %}
  {%- set offset_value = offset -%}

  {%- set results = run_query(query_template) -%}

  {% if execute %}
    {%- set results_list = results_list + results -%}
  {% endif %}
{% endfor %}

{{ results_list }}
```

### Expected Behavior

After running the build command ( dbt build -s model_name ). The model need to build.

### Steps To Reproduce

dbt build -s model_name

### Environment

```markdown
- OS: Linux-6.2
- Python: 3.11.8
- dbt-core: 1.6.10
- dbt-snowflake: 1.6.7
```

**Comment by dataders** [comment]
hi @vinod-tgm -- certainly sounds like a tricky issue you're trying to solve.

Is this a fair restatement of your problem?
> I need to build a table model off of a source table. However the source table only lets me fetch 1000 rows at a time, so I've been playing with jinja to chunk it into 1000 row chunks.


Looking at your approach, I'm not sure it will work. Ultimately a models `.sql` file and and `jinja` in it should compile to contain nothing but SQL that is sent to the warehouse. Your instinct is correct to reach for `run_query`, which we sometimes refer to as belonging to a category of "introspective queries". That is to say, `run_query` is just a tool to help generate the SQL statement.

The problem is that while the loop will fetch, ultimately there's no `SELECT` statement in the definition that the model can use to make the table.

One workaround might be to use the results of `run_query` to generate a hard-coded `SELECT` statement that contains the data that you want, but that strikes me as not the best solution.


I strongly recommend that you find a way to have a source from which you can select all the rows not just 1000 at a time. But if you're looking for more help, I recommend asking advice either on Stack Overflow or in the dbt Community Slack's [`#advice-dbt-for-power-users`](https://getdbt.slack.com/archives/C2JRRQDTL) channel.

This certainly doesn't strike me as a bug, so I'm going to close it for now. Happy to be convinced otherwise
